<div align="right" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img
 src="https://raw.githubusercontent.com/Explore-AI/Pictures/master/alx-courses/aice/assets/Content_page_banner_blue_dots.png"
 alt="ALX Content Header"
 class="full-width-image"
/>
</div>

# Subquery in  WHERE

In this notebook, we delve deeper into subqueries, specifically subqueries within a WHERE clause. One of the powerful aspects of subqueries is their ability to compare individual rows with aggregated data. This concept will be explored here.

> ⚠️ This notebook will not run on Google Colab because it cannot connect to a local database. Please make sure that this notebook is running on the same local machine as your MySQL Workbench installation and MySQL `united_nations` database.

## Learning objectives

In this train, we will learn:
- How to use the WHERE clause in subqueries.
- How to join tables.

## Connecting to our MySQL database

Using our `Access_to_Basic_Services` table in our `united_nations` database we created in MySQL Workbench, we want to answer some questions about our dataset. We can apply the same queries we used in MySQL Workbench in this notebook if we connect to our MySQL server by running the cells below.

Note that before this tutorial, we will already have worked through the lessons where the `united_nations.Basic_Services` table, `united_nations.Economic_Indicators` table, and `united_nations.Geographic_Locations` table were created.

In [1]:
# Load and activate the SQL extension to allow us to execute SQL in a Jupyter notebook. 
# If you get an error here, make sure that mysql and pymysql are installed correctly. 

%load_ext sql

c:\Users\PC\anaconda3\envs\DS_Python\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [4]:
# Establish a connection to the local database using the '%sql' magic command.
# Replace 'password' with our connection password and `db_name` with our database name. 
# If you get an error here, please make sure the database name or password is correct.

%sql mysql+pymysql://root:20!_Ke&Y@localhost:3306/united_nations


To make a query, we add the `%%sql` command to the start of a cell, create one open line then the query like below, and run the cell.

In [5]:
%%sql

SELECT 
    *
FROM
    Access_to_Basic_Services
LIMIT 5;

 * mysql+pymysql://root:***@localhost:3306/united_nations
5 rows affected.

[('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2015, Decimal('94.67'), Decimal('98.00'), Decimal('17.542806'), Decimal('184.39'), Decimal('2699700.00'), Decimal('4.93')),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2016, Decimal('94.67'), Decimal('98.00'), Decimal('17.794055'), Decimal('137.28'), Decimal('2699700.00'), Decimal('4.96')),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2017, Decimal('95.00'), Decimal('98.00'), Decimal('18.037776'), Decimal('166.81'), Decimal('2699700.00'), Decimal('4.90')),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2018, Decimal('95.00'), Decimal('98.00'), Decimal('18.276452'), Decimal('179.34'), Decimal('2699700.00'), Decimal('4.85')),
 ('Central and Southern Asia', 'Central Asia', 'Kazakhstan', 2019, Decimal('95.00'), Decimal('98.00'), Decimal('18.513673'), Decimal('181.67'), Decimal('2699700.00'), Decimal('4.80'))]

## Exercise


We want to answer the following question:

For the year 2020, which countries have a GDP above the global average, but still have less than 90% of their population with access to managed drinking water services?

This question will shed light on nations that, despite having a robust economy, may still be facing challenges in providing basic amenities like water.

### Task 1

Start by constructing a query that displays the average GDP of a country during the year 2020.

In [ ]:
%%sql

SELECT 
    AVG(Est_gdp_in_billions)
FROM 
    Economic_Indicators
WHERE 
    Time_period = 2020;

 * mysql+pymysql://root:***@localhost:3306/united_nations
1 rows affected.

[(Decimal('301.17682540'),)]

### Task 2

In order to answer our question, we need to pull data from both the Economic_Indicators and the Basic_Services tables; therefore, we need to join them together. Using `Country_name` and  `Time_period`, join the Basic_Services table to the Economic_Indicators table.

In [ ]:
%%sql

SELECT 
    e.Country_name,
    e.Time_period,
    e.Est_gdp_in_billions,
    bs.Pct_managed_drinking_water_services
FROM 
    Economic_Indicators e
INNER JOIN 
    Basic_Services bs
ON 
    e.Country_name = bs.Country_name
    AND e.Time_period = bs.Time_period
WHERE 
    e.Time_period = 2020;

 * mysql+pymysql://root:***@localhost:3306/united_nations
165 rows affected.

[('Afghanistan', 2020, Decimal('20.1400'), Decimal('80.33')),
 ('Algeria', 2020, Decimal('145.0100'), Decimal('93.33')),
 ('American Samoa', 2020, Decimal('0.7200'), Decimal('100.00')),
 ('Angola', 2020, Decimal('53.6200'), Decimal('52.33')),
 ('Argentina', 2020, Decimal('385.5400'), Decimal('100.00')),
 ('Armenia', 2020, Decimal('12.6400'), Decimal('100.00')),
 ('Australia', 2020, Decimal('1326.9000'), Decimal('100.00')),
 ('Azerbaijan', 2020, Decimal('42.6900'), Decimal('95.67')),
 ('Bahrain', 2020, Decimal('34.7200'), Decimal('100.00')),
 ('Bangladesh', 2020, Decimal('373.9000'), Decimal('97.67')),
 ('Barbados', 2020, Decimal('4.6700'), Decimal('99.00')),
 ('Belize', 2020, Decimal('2.0800'), Decimal('98.33')),
 ('Benin', 2020, Decimal('15.6500'), Decimal('65.33')),
 ('Bermuda', 2020, Decimal('6.8900'), Decimal('100.00')),
 ('Bhutan', 2020, Decimal('2.3300'), Decimal('97.33')),
 ('Bolivia (Plurinational State of)', 2020, None, Decimal('90.67')),
 ('Botswana', 2020, Decimal('14.9300'), Decimal('89.67')),
 ('Brazil', 2020, Decimal('1448.5600'), Decimal('98.33')),
 ('British Virgin Islands', 2020, None, Decimal('100.00')),
 ('Brunei Darussalam', 2020, Decimal('12.0100'), Decimal('100.00')),
 ('Burkina Faso', 2020, Decimal('17.9300'), Decimal('53.33')),
 ('Burundi', 2020, Decimal('2.6500'), Decimal('70.33')),
 ('Cabo Verde', 2020, Decimal('1.7000'), Decimal('87.33')),
 ('Cambodia', 2020, Decimal('25.8700'), Decimal('75.33')),
 ('Cameroon', 2020, Decimal('40.7700'), Decimal('64.00')),
 ('Canada', 2020, Decimal('1645.4200'), Decimal('99.00')),
 ('Central African Republic', 2020, Decimal('2.3300'), Decimal('38.33')),
 ('Chad', 2020, Decimal('10.7200'), Decimal('52.67')),
 ('Chile', 2020, Decimal('252.7300'), Decimal('100.00')),
 ('China', 2020, Decimal('14687.6700'), Decimal('93.67')),
 ('Colombia', 2020, Decimal('270.3000'), Decimal('94.67')),
 ('Congo', 2020, None, Decimal('69.00')),
 ('Cook Islands', 2020, None, Decimal('100.00')),
 ('Costa Rica', 2020, Decimal('62.1600'), Decimal('100.00')),
 ("Côte d'Ivoire", 2020, None, Decimal('70.67')),
 ('Cuba', 2020, Decimal('107.3500'), Decimal('96.33')),
 ('Cyprus', 2020, Decimal('25.0100'), Decimal('100.00')),
 ("Democratic People's Republic of Korea", 2020, None, Decimal('93.33')),
 ('Democratic Republic of the Congo', 2020, None, Decimal('47.67')),
 ('Djibouti', 2020, Decimal('3.1800'), Decimal('69.00')),
 ('Dominican Republic', 2020, Decimal('78.8400'), Decimal('95.00')),
 ('Ecuador', 2020, Decimal('99.2900'), Decimal('94.00')),
 ('Egypt', 2020, None, Decimal('99.33')),
 ('El Salvador', 2020, Decimal('24.5600'), Decimal('97.00')),
 ('Eswatini', 2020, Decimal('3.9800'), Decimal('76.67')),
 ('Ethiopia', 2020, Decimal('107.6600'), Decimal('58.00')),
 ('Falkland Islands (Malvinas)', 2020, None, Decimal('91.00')),
 ('Fiji', 2020, Decimal('4.4800'), Decimal('93.67')),
 ('French Guiana', 2020, None, Decimal('94.00')),
 ('French Polynesia', 2020, Decimal('5.7100'), Decimal('100.00')),
 ('Gabon', 2020, Decimal('15.3100'), Decimal('73.33')),
 ('Gambia', 2020, None, Decimal('79.33')),
 ('Georgia', 2020, Decimal('15.8400'), Decimal('96.67')),
 ('Ghana', 2020, Decimal('70.0400'), Decimal('84.67')),
 ('Greenland', 2020, Decimal('3.0800'), Decimal('100.00')),
 ('Guadeloupe', 2020, None, Decimal('100.00')),
 ('Guam', 2020, Decimal('5.8900'), Decimal('100.00')),
 ('Guatemala', 2020, Decimal('77.6300'), Decimal('94.00')),
 ('Guinea', 2020, Decimal('14.1800'), Decimal('67.33')),
 ('Guinea-Bissau', 2020, Decimal('1.4300'), Decimal('60.00')),
 ('Guyana', 2020, Decimal('5.4700'), Decimal('96.67')),
 ('Haiti', 2020, Decimal('14.5100'), Decimal('65.00')),
 ('Honduras', 2020, Decimal('23.8300'), Decimal('95.33')),
 ('India', 2020, Decimal('2667.6900'), Decimal('91.00')),
 ('Indonesia', 2020, Decimal('1058.6900'), Decimal('92.00')),
 ('Iran (Islamic Republic of)', 2020, None, Decimal('96.67')),
 ('Iraq', 2020, Decimal('184.3700'), Decimal('97.67')),
 ('Israel', 2020, Decimal('413.2700'), Decimal('100.00')),
 ('Jamaica', 2020, Decimal('13.8100'), Decimal('90.33')),
 ('Japan', 2020, Decimal('5040.1100'), Decimal('99.00')),
 ('Jordan', 2020, Decimal('44.1800'), Decimal('98.33')),
 ('Kazakhstan', 2020, Decimal('171.0800'), Decimal('95.00')),
 ('Kenya', 2020, Decimal('100.6700'), Decimal('67.00')),
 ('Kiribati', 2020, Decimal('0.1800'), Decimal('77.00')),
 ('Kuwait', 2020, Decimal('105.9600'), Decimal('100.00')),
 ('Kyrgyzstan', 2020, None, Decimal('92.67')),
 ("Lao People's Democratic Republic", 2020, None, Decimal('86.67')),
 ('Lebanon', 2020, Decimal('31.7100'), Decimal('93.00')),
 ('Lesotho', 2020, Decimal('2.2300'), Decimal('76.33')),
 ('Liberia', 2020, Decimal('3.0400'), Decimal('75.00')),
 ('Libya', 2020, Decimal('50.3600'), Decimal('100.00')),
 ('Madagascar', 2020, Decimal('13.0500'), Decimal('56.33')),
 ('Malawi', 2020, Decimal('12.1800'), Decimal('74.33')),
 ('Malaysia', 2020, Decimal('337.3400'), Decimal('95.33')),
 ('Maldives', 2020, Decimal('3.7500'), Decimal('99.67')),
 ('Mali', 2020, Decimal('17.4700'), Decimal('83.67')),
 ('Marshall Islands', 2020, Decimal('0.2400'), Decimal('90.00')),
 ('Martinique', 2020, None, Decimal('100.00')),
 ('Mauritania', 2020, Decimal('8.4100'), Decimal('70.33')),
 ('Mauritius', 2020, Decimal('11.4000'), Decimal('100.00')),
 ('Mayotte', 2020, None, Decimal('96.00')),
 ('Mexico', 2020, Decimal('1090.5200'), Decimal('99.33')),
 ('Mongolia', 2020, Decimal('13.3100'), Decimal('81.00')),
 ('Montserrat', 2020, None, Decimal('98.00')),
 ('Morocco', 2020, Decimal('121.3500'), Decimal('88.33')),
 ('Mozambique', 2020, Decimal('14.0300'), Decimal('66.67')),
 ('Myanmar', 2020, Decimal('78.9300'), Decimal('85.67')),
 ('Namibia', 2020, Decimal('10.5800'), Decimal('83.67')),
 ('Nauru', 2020, Decimal('0.1100'), Decimal('100.00')),
 ('Nepal', 2020, Decimal('33.4300'), Decimal('90.00')),
 ('New Caledonia', 2020, Decimal('9.4400'), Decimal('99.00')),
 ('New Zealand', 2020, Decimal('211.7300'), Decimal('100.00')),
 ('Nicaragua', 2020, Decimal('12.5900'), Decimal('79.33')),
 ('Niger', 2020, Decimal('13.7400'), Decimal('57.33')),
 ('Nigeria', 2020, Decimal('432.2000'), Decimal('77.33')),
 ('Niue', 2020, None, Decimal('97.00')),
 ('Northern Mariana Islands', 2020, None, Decimal('100.00')),
 ('Oman', 2020, Decimal('75.9100'), Decimal('87.67')),
 ('Pakistan', 2020, Decimal('300.4300'), Decimal('90.67')),
 ('Palau', 2020, Decimal('0.2500'), Decimal('100.00')),
 ('Panama', 2020, Decimal('53.9800'), Decimal('92.67')),
 ('Papua New Guinea', 2020, Decimal('23.8500'), Decimal('56.67')),
 ('Paraguay', 2020, Decimal('35.4300'), Decimal('99.67')),
 ('Peru', 2020, Decimal('201.7100'), Decimal('90.33')),
 ('Philippines', 2020, Decimal('361.7500'), Decimal('94.00')),
 ('Puerto Rico', 2020, Decimal('103.0200'), Decimal('100.00')),
 ('Qatar', 2020, Decimal('144.4100'), Decimal('100.00')),
 ('Republic of Korea', 2020, None, Decimal('100.00')),
 ('Réunion', 2020, None, Decimal('100.00')),
 ('Rwanda', 2020, Decimal('10.1800'), Decimal('66.33')),
 ('Saint Barthélemy', 2020, None, Decimal('100.00')),
 ('Saint Helena', 2020, None, Decimal('99.00')),
 ('Saint Lucia', 2020, None, Decimal('97.00')),
 ('Saint Martin (French Part)', 2020, None, Decimal('100.00')),
 ('Saint Pierre and Miquelon', 2020, None, Decimal('91.00')),
 ('Samoa', 2020, Decimal('0.8700'), Decimal('92.00')),
 ('Sao Tome and Principe', 2020, Decimal('0.4700'), Decimal('77.33')),
 ('Saudi Arabia', 2020, Decimal('703.3700'), Decimal('100.00')),
 ('Senegal', 2020, Decimal('24.4900'), Decimal('85.00')),
 ('Sierra Leone', 2020, Decimal('4.0600'), Decimal('65.00')),
 ('Singapore', 2020, Decimal('345.3000'), Decimal('100.00')),
 ('Solomon Islands', 2020, Decimal('1.5400'), Decimal('72.33')),
 ('Somalia', 2020, Decimal('6.8800'), Decimal('57.33')),
 ('South Africa', 2020, Decimal('337.6200'), Decimal('92.00')),
 ('South Sudan', 2020, None, Decimal('48.33')),
 ('Sri Lanka', 2020, Decimal('85.3500'), Decimal('94.33')),
 ('State of Palestine', 2020, None, Decimal('98.33')),
 ('Sudan', 2020, Decimal('27.0300'), Decimal('62.33')),
 ('Suriname', 2020, Decimal('2.9100'), Decimal('98.00')),
 ('Syrian Arab Republic', 2020, Decimal('11.0800'), Decimal('93.67')),
 ('Tajikistan', 2020, Decimal('8.1300'), Decimal('85.00')),
 ('Thailand', 2020, Decimal('499.6800'), Decimal('100.00')),
 ('Timor-Leste', 2020, Decimal('2.1600'), Decimal('87.00')),
 ('Togo', 2020, Decimal('7.5700'), Decimal('70.67')),
 ('Tokelau', 2020, None, Decimal('100.00')),
 ('Tonga', 2020, Decimal('0.4800'), Decimal('99.00')),
 ('Trinidad and Tobago', 2020, Decimal('21.0600'), Decimal('99.00')),
 ('Tunisia', 2020, Decimal('42.5400'), Decimal('97.00')),
 ('Türkiye', 2020, None, Decimal('96.67')),
 ('Turkmenistan', 2020, None, Decimal('100.00')),
 ('Tuvalu', 2020, Decimal('0.0600'), Decimal('100.00')),
 ('Uganda', 2020, Decimal('37.6000'), Decimal('61.00')),
 ('United Arab Emirates', 2020, Decimal('349.4700'), Decimal('100.00')),
 ('United Republic of Tanzania', 2020, None, Decimal('65.00')),
 ('United States of America', 2020, None, Decimal('100.00')),
 ('United States Virgin Islands', 2020, None, Decimal('99.00')),
 ('Uruguay', 2020, Decimal('53.5600'), Decimal('98.00')),
 ('Uzbekistan', 2020, Decimal('59.8900'), Decimal('98.00')),
 ('Vanuatu', 2020, Decimal('0.9000'), Decimal('93.00')),
 ('Venezuela (Bolivarian Republic of)', 2020, None, Decimal('94.00')),
 ('Viet Nam', 2020, None, Decimal('97.33')),
 ('Wallis and Futuna Islands', 2020, None, Decimal('99.00')),
 ('Yemen', 2020, None, Decimal('63.00')),
 ('Zambia', 2020, Decimal('18.1100'), Decimal('66.67')),
 ('Zimbabwe', 2020, Decimal('21.5100'), Decimal('68.00'))]

### Task 3

Using the query created in Task 2, filter the results to display records where:

1. The year = 2020.
2. The GDP is above the global average. 
3. Less than 90% of the country's population have access to managed drinking water services. 

Hint: Keep in mind that we determined the GDP above the global average in Task 1.

In [18]:
%%sql

SELECT 
    e.Country_name,
    e.Time_period,
    e.Est_gdp_in_billions,
    bs.Pct_managed_drinking_water_services
FROM 
    Economic_Indicators e
INNER JOIN 
    Basic_Services bs
ON 
    e.Country_name = bs.Country_name
    AND e.Time_period = bs.Time_period
WHERE 
    e.Time_period = 2020
    AND e.Est_gdp_in_billions > (SELECT 
                                    AVG(Est_gdp_in_billions)
                                FROM 
                                    Economic_Indicators
                                WHERE 
                                    Time_period = 2020)
    AND bs.Pct_managed_drinking_water_services < 90;

 * mysql+pymysql://root:***@localhost:3306/united_nations
1 rows affected.

[('Nigeria', 2020, Decimal('432.2000'), Decimal('77.33'))]

## Solutions

### Task 1

In [ ]:
%%sql

SELECT 
    AVG(Est_gdp_in_billions)
FROM 
    Economic_Indicators 
WHERE 
    Time_period = 2020;

### Task 2

In [ ]:
%%sql

SELECT 
    econ.Country_name,
    econ.Time_period,
    econ.Est_gdp_in_billions,
    service.Pct_managed_drinking_water_services
FROM 
    Economic_Indicators AS econ
INNER JOIN 
    Basic_Services AS service
ON 
    econ.Country_name = service.Country_name
    AND econ.Time_period = service.Time_period
LIMIT 10;

### Task 3

In [ ]:
%%sql

SELECT 
    econ.Country_name,
    econ.Time_period,
    econ.Est_gdp_in_billions,
    service.Pct_managed_drinking_water_services
FROM 
    Economic_Indicators AS econ
INNER JOIN 
    Basic_Services AS service
ON 
    econ.Country_name = service.Country_name
    AND econ.Time_period = service.Time_period
WHERE
    econ.time_period = 2020
    AND service.Pct_managed_drinking_water_services < 90
    AND econ.Est_gdp_in_billions > (SELECT 
                                        AVG(Est_gdp_in_billions)
                                    FROM 
                                        Economic_Indicators 
                                    WHERE 
                                        Time_period = 2020);

## Summary

This layered query first calculates the average GDP and then uses that value to filter out countries, along with all of the other criteria. 
Nigeria is the only country that satisfies this criteria. While its GDP might be above average, the low access to water is linked to policies that are not aligned with SDG 6, bad governance, infrastructure, quality, and supply, according to the World Bank.
Finally, note that these queries quickly become complex when we use JOINs, subqueries, filters, and calculations together. The code is hard to read now and will be even harder to read for someone else who might work on this later. So we need to be mindful of this as we create these complex queries.

#  

<div align="center" style=" font-size: 80%; text-align: center; margin: 0 auto">
<img src="https://raw.githubusercontent.com/Explore-AI/Pictures/refs/heads/master/ALX_banners/ALX_Navy.png"  style="width:100px"  ;/>
</div>